### ISSUE TITLE
some EEN Cooperation profiles do not appear after update

### ISSUE THREAD

**Issue by francescoEUR** [eSCT/oppfin#8]
When updating the EEN data, some of the cooperation profiles do not appear in the Cooperations presex.
Ex. update on 20.1, 8 EEN Cooperation records appear in Opp-Fin:
- MG-5-2-2017: Innovative ICT solutions for future logistics operations
- IAM Improved Assessability Modules for persons with neurological or cognitive disabilities.
- HERA Open Collaborative Platform
- ISICDA Imaging System for Improved Cancer disease Diagnosis Aid
- ICT–39-2017: International partnership building in low and middle income countries
- Smart Governance Monitor
- Software Defined Execution Environment for Big Data Processing Systems
- Time and Energy Analysis for Multicore/Manycore Processors (TeamPlay)

but other profiles like:
- PS-PL-103846 Quantum sensing with massive and fast entangled atoms from dissociation of rotationally and vibrationally cold dimers in supersonic beams
or 
- PS-UK-103696 Innovation of patient specific quantum learning architecture for enhancing real-time brain-computer interface (BCI)

do not appear.

(see Ideal-Ist page http://www.ideal-ist.eu/partner-search/pssearch )

It could be that since those profiles are not "quality labeled" these are not distributed over the web service.

please invesitage

**Comment by anhnn-nextg** [comment]
After synchronize idealistCooperations collection i found both PS-PL-103846 and PS-UK-103696

**Comment by francescoEUR** [comment]
I checked again today 23.6.2017 and still have the issue:

in [http://www.ideal-ist.eu/partner-search/pssearch](http://www.ideal-ist.eu/partner-search/pssearch) I see:
PS-IT-103246
PS-IT-104713
PS-MK-104186
PS-DE-102993

and a  much more which are not "quality labeled" partner searches like:
PS-HU-104301
PS-PT-104250
PS-TR-104146

Why those do not show-up in the opportunity-finder in preset cooperations?
In opp-fin I only see ps-it-103246 .

Is it because of the deadline date which is in the past?

please analyse

**Comment by anhnn-nextg** [comment]
I have been checked, those do not show-up in the opportunity-finder in preset cooperations because of the deadline date was in the past or they didn't have deadline date.
It still could be found if you search all

**Comment by francescoEUR** [comment]
tanks for checking Anh
